[default]
description = "Default permissions for the androidblock plugin"
permissions = [
    "allow-get-state",
    "allow-save-schedule",
    "allow-delete-schedule",
    "allow-toggle-schedule",
    "allow-get-installed-apps",
    "allow-open-accessibility-settings",
    "allow-open-battery-settings",
]
